name: Publish on private repo
on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flit wheel
      - name: Build and publish
        run: |
          export FLIT_USERNAME=__token__
          export FLIT_PASSWORD=${{ secrets.PYPI_TOKEN }}
          set -x
          flit publish
